{
    'name': 'CRM Menu Override',
    'version': '1.0',
    'category': 'CRM',
    "author": "Yosr Belkhouja",
    'summary': 'Override Leads menu',
    'license': 'LGPL-3',
    'depends': ['crm',
        'sale_crm',
        'sale',
        'account',
        'hr',
    'crm_lead_code_update'],
    'data': [
        'security/ir.model.access.csv',
         'views/piste_source_view.xml',
    'views/opportunity_workflow_view.xml',  
    'views/crm_menu_override.xml',
    'views/crm_lead_pistes_view.xml',
    ],
    'installable': True,
    'auto_install': False,
}
